jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: mkdir test && echo "adding lines to divya file" > test/divya.sh
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: test
          to: 's3://divyabu/prefix'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: test/divya.sh
          to: 's3://divyabu'
orbs:
  aws-s3: circleci/aws-s3@2.0.0
version: 2.1
